### PR TITLE
fix: ecosystems validate external references urls

### LINKED ISSUE #96: Ecosyste.ms returns invalid URL for package homepage
This is similar to #84.

Ecosyste.ms returns an invalid URL in `.homepage` for package with `purl=pkg:npm/%40mui/utils@5.16.6`. See:
```
❯ curl -sS -G --data-urlencode "purl=pkg:npm/%40mui/utils@5.16.6" 'https://packages.ecosyste.ms/api/v1/packages/lookup' \
  | jq '.[].homepage'
"http://private package"
```

The value is then used by parlay to set the `<package>.externalReferences[].url` with `type=website`:

https://github.com/snyk/parlay/blob/bc55e4def82d7bfe71335b538833d1773c5f229c/lib/ecosystems/enrich_cyclonedx.go#L95-L97

https://github.com/snyk/parlay/blob/bc55e4def82d7bfe71335b538833d1773c5f229c/lib/ecosystems/enrich_cyclonedx.go#L68-L81

I can work on a fix, but I'm unsure on the direction you may prefer.

My idea is to use the Go stdlib to check for the validity of the URL in `enrichExternalReference` and silently skip invalid ones; unfortunately I'm not sure if this would break some assumptions or if it would break the CycloneDX format. Any advice would be highly appreciated.

### PR DESCRIPTION
**Pull request by acidghost**
Fixes #96.

### CODE REVIEW

File: lib/ecosystems/enrich_cyclonedx.go [hunk 1]
```diff
@@ -69,6 +70,9 @@ func enrichExternalReference(comp *cdx.Component, url *string, refType cdx.Exter
 	if url == nil {
 		return
 	}
+	if _, err := gourl.Parse(*url); err != nil {
```
Comment (mcombuechen) [inline lib/ecosystems/enrich_cyclonedx.go:73]: nit: can we use the std import name `url` and rename this argument instead to `ref`?

**Review by mcombuechen — COMMENTED** [review]
Thanks for the contribution @acidghost 🙏 

I think the approach looks good. Just one tiny nit 😄

**Review by mcombuechen — APPROVED** [review]
