### PR TITLE
fix: return ecosyste.ms license based on package version

### LINKED ISSUE #87: Parlay doesn't seem to respect version number when determining license
Hello!

I've noticed an issue with NPM package `ua-parser-js@0.7.1`. This package changed from the MIT license to AGPL in its v2.0.0 release. 

I'm running `syft` to generate the SBOM for the project, and it concludes 
```json
      "licenses": [
        {
          "license": {
            "id": "MIT"
          }
        },
        {
          "license": {
            "name": "GPLv2"
          }
        }
      ]
```

When I then run`parlay e enrich` on the SBOM it overwrites the license to `"expression": "AGPL-3.0-or-later"` which is correct for v2.0.0 but not for `"version": "0.7.1"` which is the version referenced in the SBOM.

Can this be fixed? I'm not sure if the issue is in parlay or in ecosyste.ms, and apologise if it's on their end.

Furthermore, is there some way to ensure that parlay doesn't overwrite the license field if it exists? 

Thank you for the tool, it's been very helpful apart from this!

### PR DESCRIPTION
**Pull request by paulrosca-snyk**
When enriching with ecosyste.ms, fetch the license based on the package version.

Closes #87

### CODE REVIEW

File: lib/ecosystems/package.go [hunk 1]
```diff
@@ -47,6 +47,26 @@ func GetPackageData(purl packageurl.PackageURL) (*packages.GetRegistryPackageRes
...
+func GetPackageVersionData(purl packageurl.PackageURL) (*packages.GetRegistryPackageVersionResponse, error) {
+	client, err := packages.NewClientWithResponses(server)
+	if err != nil {
+		return nil, err
+	}
+
+	// Ecosyste.ms has a purl based API, but unfortunately slower
+	// so we break the purl down to registry and name values locally
+	// params := packages.LookupPackageParams{Purl: &p}
+	// resp, err := client.LookupPackageWithResponse(context.Background(), &params)
```
Comment (mcombuechen) [inline lib/ecosystems/package.go:59]: can we remove this? including the comment about the purl api? i don't find it particularly useful 😄

File: lib/ecosystems/enrich_cyclonedx.go [hunk 2]
```diff
@@ -47,16 +47,20 @@ var cdxEnrichers = []cdxEnricher{
...
 	}
 }
 
-func enrichCDXLicense(comp *cdx.Component, data *packages.Package) {
-	if data.NormalizedLicenses != nil {
-		if len(data.NormalizedLicenses) > 0 {
-			expression := data.NormalizedLicenses[0]
+func enrichCDXLicense(comp *cdx.Component, data *packages.Version) {
+	if data.Licenses != nil {
+		if *data.Licenses != "" {
```
Comment (mcombuechen) [inline lib/ecosystems/enrich_cyclonedx.go:62]: this looks a bit like a red flag. don't we have `data.NormalizedLicenses` on the package version response? this change would mean that we are potentially enriching with unsanitized data. e.g. `MIT,Apache-2.0` is not a valid SPDX license expression.

Comment (paulrosca-snyk) [reply lib/ecosystems/enrich_cyclonedx.go:62]: looks like the `ecosyste.ms` response for a specific package version doesn't have a normalised licenses field, no

Comment (mcombuechen) [reply lib/ecosystems/enrich_cyclonedx.go:62]: I raised an issue with ecosyste.ms about this here: https://github.com/ecosyste-ms/packages/issues/960

Comment (mcombuechen) [reply lib/ecosystems/enrich_cyclonedx.go:62]: @paulrosca-snyk could we move forward with this approach, but `strings.Split()` the value and build an SPDX license expression with `strings.Join()`? The current behaviour is to concatenate with an `OR`, but [we have an open issue on this](https://github.com/snyk/parlay/issues/77) and should switch to `AND`.

Comment (paulrosca-snyk) [reply lib/ecosystems/enrich_cyclonedx.go:62]: @mcombuechen definitely, but are we sure we want to proceed with the `AND` change, it doesn't seem like it will fix the issue, just change it in the other direction (i.e we'll be reporting `OR` clauses incorrectly as `AND`, but maybe that's better than the current behaviour?)

Comment (paulrosca-snyk) [reply lib/ecosystems/enrich_cyclonedx.go:62]: From my understanding they can be either and we just don't get this information back from ecosyste.ms (assuming they even have it stored)

**Review by mcombuechen — APPROVED** [review]
